name: Build
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate code coverage files
        run: make codecov

      - name: Upload to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          fail_ci_if_error: true

      - name: Setup Hugo
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: "0.82.0"
          extended: true

      - name: Build Documentation
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make doc-generate

      - name: Deploy Documentation
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs/public
        with:
          emptyCommits: false

      - name: Build Tag
        if: github.ref != 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sL https://git.io/goreleaser | bash;
