name: Build Pull Request
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate code coverage files
        run: make codecov

      - name: Upload to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          fail_ci_if_error: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: "0.82.0"
          extended: true

      - name: Test Documentation
        run: |
          make doc-generate
